### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by def750** [skylandersNFC/NFC-Copy#1]
Could you please open source code for wCopy software or at least make further documentation on how NS106 card reader works so people can make their own software for it more easly?

**Comment by skylandersNFC** [comment]
This software is developed by a Chinese company. When you purchase a device from them, they typically provide a Google Drive link or another website to download the software. However, they only offer the compiled version, not the source code, which I don't believe is available anywhere.

I've shared the software here to ensure its availability and preservation. I also have a tutorial on how to use the NS106 with this software for Skylanders.

If you have expertise in this area, please feel free to contribute any documentation or findings related to the device or software.

Thank you!
